services:
  web:
    image: alexlerche/itu_minitwit:latest
    container_name: minitwit_web
    restart: always
    environment:
      MINITWIT_DB_CONNECTION_STRING:
        Host=${MINITWIT_DB_HOST};Username=${MINITWIT_DB_USER};Password=${MINITWIT_DB_PASSWORD};Database=${MINITWIT_DB_NAME}
    ports:
      - 8080:8080
    volumes:
      - minitwit_app_data:/data

  nginx:
    image: nginx:latest
    container_name: minitwit_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      web:
        condition: service_started

volumes:
  minitwit_app_data:
