services:
  db:
    image: postgres:17
    container_name: minitwit_psql
    restart: always
    environment:
      POSTGRES_USER: ${MINITWIT_DB_USER}
      POSTGRES_PASSWORD: ${MINITWIT_DB_PASSWORD}
      POSTGRES_DB: ${MINITWIT_DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${MINITWIT_DB_USER}", "-d", "${MINITWIT_DB_NAME}"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3
    ports:
      - 5432:5432
    volumes:
      - minitwit_pg_data:/var/lib/postgresql/data

volumes:
  minitwit_pg_data:
