name: Docker Image CI

on:
  push:
    branches: [ "staging" ]
    paths:
      - 'WebServer/**'  # Only trigger if files inside WebServer/ change
  pull_request:
    branches: [ "staging" ]
    paths:
      - 'WebServer/**'  # Only trigger if files inside WebServer/ change

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build the Docker image
      run: docker build WebServer --file WebServer/Dockerfile --tag alexlerche/itu_minitwit:latest

    - name: Push Docker image to Docker Hub
      run: docker push alexlerche/itu_minitwit:latest
