name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - WebServer/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET SDK
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          sudo apt-get update -y
          sudo apt-get install -y dotnet-sdk-9.0

      - name: Publish WebServer
        run: dotnet publish WebServer/MiniTwit.csproj -c Release -o WebServer/publish

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build WebServer -f WebServer/Dockerfile -t mrphil2105/minitwit_web:latest

      - name: Push Docker image
        run: docker push mrphil2105/minitwit_web:latest

  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tex/main.tex
          working_directory: report
          args: -pdf -outdir=build

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: report/build/main.pdf
