name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - WebServer/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install .NET SDK
      run: apt-get install -y dotnet-sdk-9.0

    - name: Publish WebServer
      run: dotnet publish WebServer/MiniTwit.csproj -c Release -o WebServer/publish
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: docker build WebServer --file WebServer/Dockerfile --tag alexlerche/itu_minitwit:latest

    - name: Push Docker image
      run: docker push alexlerche/itu_minitwit:latest
