name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - WebServer/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET SDK
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          sudo apt-get update -y
          sudo apt-get install -y dotnet-sdk-9.0

      - name: Publish WebServer
        run: dotnet publish WebServer/MiniTwit.csproj -c Release -o WebServer/publish

      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libxss1 libasound2 libxcomposite1 libxrandr2 libgbm1 libgtk-3-0

      - name: Install Playwright Browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          export PATH="$PATH:$HOME/.dotnet/tools"
          cd Tests/ui/api/integration/MiniTwit.UI.Tests
          playwright install

      - name: Run UI tests
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet test Tests/ui/api/integration/MiniTwit.UI.Tests/MiniTwit.UI.Tests.csproj --logger "console;verbosity=detailed"

      - name: Run API tests
        run: |
          dotnet test Tests/api-tests/MiniTwit.API.Tests/MiniTwit.API.Tests.csproj --logger "console;verbosity=detailed"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build WebServer -f WebServer/Dockerfile -t mrphil2105/minitwit_web:latest

      - name: Push Docker image
        run: docker push mrphil2105/minitwit_web:latest
