name: Build docs

on: push

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/core:2.9
        with:
          args: pandoc report/tex/main.tex -o report/build/main.pdf --pdf-engine=xelatex
