name: Report Build

on:
  push:
    branches:
      - main
    paths:
      - report/**

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tex/main.tex
          working_directory: report
          args: -pdf -outdir=build

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: report/build/main.pdf
