name: Build LaTeX PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: docker://pandoc/core:3.7
        with:
          args: "./report/tex/main.tex -o ./report/build/main.pdf --pdf-engine=xelatex"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: report/build/main.pdf
