name: Report Build

on: push

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create build directory
        run: mkdir -p report/build

      - name: Compile LaTeX to PDF using Pandoc Docker
        uses: docker://pandoc/core:2.9
        with:
          args: ./report/tex/main.tex -o ./report/build/main.pdf --pdf-engine=xelatex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: report/build/main.pdf
