name: Build docs

on: push

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX to PDF
        uses: docker://blang/latex:ubuntu
        with:
          args: xelatex -output-directory=report/build report/tex/main.tex
